FROM nginx:alpine

LABEL maintainer="CiboAtlas / UNCORRELATED-TRACK-PROCESSING"
LABEL description="Static site for UCTP Analytic Console"

RUN rm -rf /usr/share/nginx/html/*

COPY . /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]